language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - node
script:
  - npm run test:prod && npm run build
after_success:
  - npm run report-coverage

deploy:
  - provider: script
    skip_cleanup: true
    script: npx semantic-release && node tools/publish-gh-page.js
    on:
     branch: master
